version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: postgres-container
    ports:
      - "5432:5432"
    network_mode: host
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=postgres
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_PORT=5432
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init.sql