SUCCESS_MSG_RESPONSE = "File uploaded successfully"
FAIL_VALIDATION_FAIL = "File Validation Failed"
RETRIEVE_EMPLOYEE_FAILED = "Retrieve employee information failed"
HTTP_SUCCESS_STATUS = 200
HTTP_FAIL_STATUS = 400
MINIMUM_ROW_COUNT = 5
VALID_LINE_INPUT = 4
DB_SUCCESS_OPERATION = "OK"
DB_FAILED_OPERATION = "Failed"
REQUIRED_PARAMS = ["minSalary", "maxSalary", "offset", "limit", "sort"]
